"""
finetune/data/prepare_sft.py
-----------------------------
Download and format SFT datasets for chat and code fine-tuning.

Formats all data into the SLM chat template:
    <|system|>{system}<|endofturn|>
    <|user|>{user}<|endofturn|>
    <|assistant|>{assistant}<|endofturn|>

Stage 1 — Chat SFT:
    Dataset: teknium/OpenHermes-2.5
    Size:    ~1M examples
    Output:  data/sft/chat/train.jsonl + val.jsonl

Stage 2 — Code SFT:
    Dataset: ise-uiuc/Magicoder-OSS-Instruct-75K
    Size:    ~75k examples
    Output:  data/sft/code/train.jsonl + val.jsonl

Output format — one conversation per line:
    {
        "conversations": [
            {"role": "system",    "content": "..."},
            {"role": "user",      "content": "..."},
            {"role": "assistant", "content": "..."}
        ],
        "source": "openhermes"
    }

Usage:
    python finetune/data/prepare_sft.py --stage both
    python finetune/data/prepare_sft.py --stage chat
    python finetune/data/prepare_sft.py --stage code
"""

import argparse
import json
import logging
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)

DATA_DIR = Path(os.environ.get("DATA_DIR", "data"))
SFT_DIR = DATA_DIR / "sft"

# Default system prompt
DEFAULT_SYSTEM = "You are a helpful, harmless, and honest assistant."
CODE_SYSTEM = "You are an expert programming assistant. Write clean, efficient, and well-documented code."


# ── Chat template ──────────────────────────────────────────────────────────────

def format_conversation(messages: list[dict]) -> str:
    """
    Format a list of messages into the SLM chat template string.

    Args:
        messages: List of {"role": ..., "content": ...} dicts.

    Returns:
        Formatted chat string with special tokens.
    """
    parts = []
    for msg in messages:
        role = msg["role"]
        content = msg["content"].strip()
        if role == "system":
            parts.append(f"<|system|>{content}<|endofturn|>")
        elif role == "user":
            parts.append(f"<|user|>{content}<|endofturn|>")
        elif role == "assistant":
            parts.append(f"<|assistant|>{content}<|endofturn|>")
    return "".join(parts)


def write_jsonl(records: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for record in records:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
    log.info(f"Wrote {len(records):,} records to {path}")


# ── Chat SFT — OpenHermes-2.5 ─────────────────────────────────────────────────

def prepare_chat(val_fraction: float = 0.02) -> None:
    """
    Download and format OpenHermes-2.5 for chat SFT.

    OpenHermes-2.5 is a high-quality synthetic instruction dataset
    generated by GPT-4. Contains diverse instruction-following examples
    across coding, reasoning, creative writing, and general knowledge.

    Format: each example has a "conversations" field with role/value pairs.
    """
    from datasets import load_dataset

    out_dir = SFT_DIR / "chat"
    train_path = out_dir / "train.jsonl"
    val_path = out_dir / "val.jsonl"

    if train_path.exists() and val_path.exists():
        log.info(f"Chat SFT data already exists at {out_dir}")
        return

    log.info("Loading OpenHermes-2.5...")
    dataset = load_dataset("teknium/OpenHermes-2.5", split="train")
    log.info(f"OpenHermes-2.5: {len(dataset):,} examples")

    records = []
    skipped = 0

    for example in dataset:
        conversations = example.get("conversations", [])
        if not conversations:
            skipped += 1
            continue

        # Convert from OpenHermes format (role=human/gpt) to SLM format
        messages = []

        # Add system prompt if present
        system = example.get("system_prompt", "").strip()
        if system:
            messages.append({"role": "system", "content": system})
        else:
            messages.append({"role": "system", "content": DEFAULT_SYSTEM})

        valid = True
        for turn in conversations:
            role = turn.get("from", turn.get("role", "")).lower()
            content = turn.get("value", turn.get("content", "")).strip()

            if not content:
                valid = False
                break

            if role in ("human", "user"):
                messages.append({"role": "user", "content": content})
            elif role in ("gpt", "assistant"):
                messages.append({"role": "assistant", "content": content})

        if not valid or len(messages) < 2:
            skipped += 1
            continue

        # Must end with assistant turn
        if messages[-1]["role"] != "assistant":
            skipped += 1
            continue

        records.append({
            "conversations": messages,
            "text": format_conversation(messages),
            "source": "openhermes",
        })

    log.info(f"Processed: {len(records):,} kept, {skipped:,} skipped")

    # Split
    n_val = max(1000, int(len(records) * val_fraction))
    import random
    random.seed(42)
    random.shuffle(records)
    val_records = records[:n_val]
    train_records = records[n_val:]

    write_jsonl(train_records, train_path)
    write_jsonl(val_records, val_path)

    log.info(f"Chat SFT: {len(train_records):,} train, {len(val_records):,} val")


# ── Code SFT — Magicoder-OSS-Instruct ─────────────────────────────────────────

def prepare_code(val_fraction: float = 0.05) -> None:
    """
    Download and format Magicoder-OSS-Instruct-75K for code SFT.

    Magicoder generates coding problems inspired by real open-source code,
    then generates solutions. Higher quality and diversity than CodeAlpaca.
    Each example is a single-turn instruction/response pair.
    """
    from datasets import load_dataset

    out_dir = SFT_DIR / "code"
    train_path = out_dir / "train.jsonl"
    val_path = out_dir / "val.jsonl"

    if train_path.exists() and val_path.exists():
        log.info(f"Code SFT data already exists at {out_dir}")
        return

    log.info("Loading Magicoder-OSS-Instruct-75K...")
    dataset = load_dataset("ise-uiuc/Magicoder-OSS-Instruct-75K", split="train")
    log.info(f"Magicoder: {len(dataset):,} examples")

    records = []
    skipped = 0

    for example in dataset:
        instruction = example.get("problem", "").strip()
        solution = example.get("solution", "").strip()

        if not instruction or not solution:
            skipped += 1
            continue

        # Wrap solution in code tags if it looks like code
        if any(kw in solution for kw in ["def ", "class ", "import ", "function ", "```"]):
            # Extract code blocks if already formatted with backticks
            if "```" in solution:
                assistant_content = solution
            else:
                lang = _detect_language(solution)
                assistant_content = f"<|code|>\n{solution}\n<|endofcode|>"
        else:
            assistant_content = solution

        messages = [
            {"role": "system", "content": CODE_SYSTEM},
            {"role": "user", "content": instruction},
            {"role": "assistant", "content": assistant_content},
        ]

        records.append({
            "conversations": messages,
            "text": format_conversation(messages),
            "source": "magicoder",
        })

    log.info(f"Processed: {len(records):,} kept, {skipped:,} skipped")

    # Split
    n_val = max(500, int(len(records) * val_fraction))
    import random
    random.seed(42)
    random.shuffle(records)
    val_records = records[:n_val]
    train_records = records[n_val:]

    write_jsonl(train_records, train_path)
    write_jsonl(val_records, val_path)

    log.info(f"Code SFT: {len(train_records):,} train, {len(val_records):,} val")


def _detect_language(code: str) -> str:
    """Simple heuristic to detect programming language."""
    if "def " in code or "import " in code or "print(" in code:
        return "python"
    if "function " in code or "const " in code or "let " in code:
        return "javascript"
    if "public class " in code or "void " in code:
        return "java"
    return "python"


# ── CLI ────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Prepare SFT datasets")
    parser.add_argument(
        "--stage",
        choices=["chat", "code", "both"],
        default="both",
        help="Which SFT stage to prepare",
    )
    parser.add_argument(
        "--val-fraction",
        type=float,
        default=0.02,
        help="Fraction of data to use for validation",
    )
    args = parser.parse_args()

    if args.stage in ("chat", "both"):
        log.info("=== Preparing Chat SFT data (OpenHermes-2.5) ===")
        prepare_chat(val_fraction=args.val_fraction)

    if args.stage in ("code", "both"):
        log.info("=== Preparing Code SFT data (Magicoder-OSS-Instruct) ===")
        prepare_code(val_fraction=args.val_fraction)

    log.info("SFT data preparation complete.")
    log.info(f"Output: {SFT_DIR}")


if __name__ == "__main__":
    main()