"""
finetune/data/prepare_sft.py
-----------------------------
Download and format SFT datasets for chat and code fine-tuning.

Formats all data into the SLM conversation format:
    [
        {"role": "system",    "content": "..."},
        {"role": "user",      "content": "..."},
        {"role": "assistant", "content": "..."}
    ]

The "text" field is intentionally omitted. train_sft.py applies
tokenizer.apply_chat_template() at training time via a formatting_func
passed to SFTTrainer — the same code path used during inference.
Pre-formatting with a manual formatter would bypass the tokenizer's
baked-in chat template and produce the wrong training format.

Stage 1 — Chat SFT:
    Dataset: teknium/OpenHermes-2.5
    Size:    ~1M examples
    Output:  data/sft/chat/train.jsonl + val.jsonl

Stage 2 — Code SFT:
    Dataset: ise-uiuc/Magicoder-OSS-Instruct-75K
    Size:    ~75k examples
    Output:  data/sft/code/train.jsonl + val.jsonl

Output format — one conversation per line:
    {
        "conversations": [
            {"role": "system",    "content": "..."},
            {"role": "user",      "content": "..."},
            {"role": "assistant", "content": "..."}
        ],
        "source": "openhermes"
    }

Usage:
    python finetune/data/prepare_sft.py --stage both
    python finetune/data/prepare_sft.py --stage chat
    python finetune/data/prepare_sft.py --stage code
"""

import argparse
import json
import logging
import os
import random
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)

DATA_DIR = Path(os.environ.get("DATA_DIR", "data"))
SFT_DIR  = DATA_DIR / "sft"

# Default system prompts
DEFAULT_SYSTEM = "You are a helpful, harmless, and honest assistant."
CODE_SYSTEM    = "You are an expert programming assistant. Write clean, efficient, and well-documented code."


def write_jsonl(records: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for record in records:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
    log.info(f"Wrote {len(records):,} records to {path}")


# ── Chat SFT — OpenHermes-2.5 ─────────────────────────────────────────────────

def prepare_chat(val_fraction: float = 0.02) -> None:
    """
    Download and format OpenHermes-2.5 for chat SFT.

    OpenHermes-2.5 is a high-quality synthetic instruction dataset
    generated by GPT-4. Contains diverse instruction-following examples
    across coding, reasoning, creative writing, and general knowledge.

    Format: each example has a "conversations" field with role/value pairs.
    """
    from datasets import load_dataset

    out_dir    = SFT_DIR / "chat"
    train_path = out_dir / "train.jsonl"
    val_path   = out_dir / "val.jsonl"

    if train_path.exists() and val_path.exists():
        log.info(f"Chat SFT data already exists at {out_dir}")
        return

    log.info("Loading OpenHermes-2.5...")
    dataset = load_dataset("teknium/OpenHermes-2.5", split="train")
    log.info(f"OpenHermes-2.5: {len(dataset):,} examples")

    records = []
    skipped = 0

    for example in dataset:
        conversations = example.get("conversations") or []
        if not conversations:
            skipped += 1
            continue

        messages = []

        # Add system prompt — use `or ""` to handle None values
        system = (example.get("system_prompt") or "").strip()
        messages.append({
            "role": "system",
            "content": system if system else DEFAULT_SYSTEM,
        })

        valid = True
        for turn in conversations:
            # Use `or ""` to handle None values in role and content fields
            role    = (turn.get("from") or turn.get("role") or "").lower()
            content = (turn.get("value") or turn.get("content") or "").strip()

            if not content:
                valid = False
                break

            if role in ("human", "user"):
                messages.append({"role": "user", "content": content})
            elif role in ("gpt", "assistant"):
                messages.append({"role": "assistant", "content": content})

        if not valid or len(messages) < 2:
            skipped += 1
            continue

        # Must end with assistant turn
        if messages[-1]["role"] != "assistant":
            skipped += 1
            continue

        records.append({
            "conversations": messages,
            "source": "openhermes",
        })

    log.info(f"Processed: {len(records):,} kept, {skipped:,} skipped")

    # Split
    n_val = max(1000, int(len(records) * val_fraction))
    random.seed(42)
    random.shuffle(records)
    val_records   = records[:n_val]
    train_records = records[n_val:]

    write_jsonl(train_records, train_path)
    write_jsonl(val_records, val_path)

    log.info(f"Chat SFT: {len(train_records):,} train, {len(val_records):,} val")


# ── Code SFT — Magicoder-OSS-Instruct ─────────────────────────────────────────

def prepare_code(val_fraction: float = 0.05) -> None:
    """
    Download and format Magicoder-OSS-Instruct-75K for code SFT.

    Magicoder generates coding problems inspired by real open-source code,
    then generates solutions. Higher quality and diversity than CodeAlpaca.
    Each example is a single-turn instruction/response pair.
    """
    from datasets import load_dataset

    out_dir    = SFT_DIR / "code"
    train_path = out_dir / "train.jsonl"
    val_path   = out_dir / "val.jsonl"

    if train_path.exists() and val_path.exists():
        log.info(f"Code SFT data already exists at {out_dir}")
        return

    log.info("Loading Magicoder-OSS-Instruct-75K...")
    dataset = load_dataset("ise-uiuc/Magicoder-OSS-Instruct-75K", split="train")
    log.info(f"Magicoder: {len(dataset):,} examples")

    records = []
    skipped = 0

    for example in dataset:
        # Use `or ""` to handle None values
        instruction = (example.get("problem") or "").strip()
        solution    = (example.get("solution") or "").strip()

        if not instruction or not solution:
            skipped += 1
            continue

        # Wrap solution in code tags if it looks like code
        if any(kw in solution for kw in ["def ", "class ", "import ", "function ", "```"]):
            if "```" in solution:
                assistant_content = solution
            else:
                assistant_content = f"<|code|>\n{solution}\n<|endofcode|>"
        else:
            assistant_content = solution

        messages = [
            {"role": "system",    "content": CODE_SYSTEM},
            {"role": "user",      "content": instruction},
            {"role": "assistant", "content": assistant_content},
        ]

        records.append({
            "conversations": messages,
            "source": "magicoder",
        })

    log.info(f"Processed: {len(records):,} kept, {skipped:,} skipped")

    # Split
    n_val = max(500, int(len(records) * val_fraction))
    random.seed(42)
    random.shuffle(records)
    val_records   = records[:n_val]
    train_records = records[n_val:]

    write_jsonl(train_records, train_path)
    write_jsonl(val_records, val_path)

    log.info(f"Code SFT: {len(train_records):,} train, {len(val_records):,} val")


# ── CLI ────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Prepare SFT datasets")
    parser.add_argument(
        "--stage",
        choices=["chat", "code", "both"],
        default="both",
        help="Which SFT stage to prepare",
    )
    parser.add_argument(
        "--val-fraction",
        type=float,
        default=0.02,
        help="Fraction of data to use for validation",
    )
    args = parser.parse_args()

    if args.stage in ("chat", "both"):
        log.info("=== Preparing Chat SFT data (OpenHermes-2.5) ===")
        prepare_chat(val_fraction=args.val_fraction)

    if args.stage in ("code", "both"):
        log.info("=== Preparing Code SFT data (Magicoder-OSS-Instruct) ===")
        prepare_code(val_fraction=args.val_fraction)

    log.info("SFT data preparation complete.")
    log.info(f"Output: {SFT_DIR}")


if __name__ == "__main__":
    main()