name: slm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10.14
  - pip=24.0
  - pytorch::pytorch=2.1.2
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision=0.16.2
  - cudatoolkit=12.1
  - gcc=11.4
  - gxx=11.4

  - pip:
    - -r requirements.txt
