"""Internal Accelerate DDP config generation, invoked by make config-gen.

Single-GPU launches use single_gpu.yaml; GPUS>1 generates multi_gpu.yaml.
"""
from __future__ import annotations
import argparse
import datetime as dt
from pathlib import Path


def render_ddp(num_gpus: int, mixed_precision: str = "bf16") -> str:
    timestamp = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""# ─────────────────────────────────────────────────────────────────────────────
# Auto-generated by config_gen/accel_gen.py
# Strategy:   ddp (DistributedDataParallel — model replicated per GPU)
# Generated:  {timestamp}
#
# Each GPU must hold one complete model/optimizer replica.
# ─────────────────────────────────────────────────────────────────────────────
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
enable_cpu_affinity: false
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: {mixed_precision}
num_machines: 1
num_processes: {num_gpus}
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
"""



def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gpus", type=int, required=True)
    parser.add_argument("--mixed-precision", choices=["bf16", "fp16", "no"], default="bf16")
    parser.add_argument("--output", "-o", type=Path, default=Path("accelerate_configs/multi_gpu.yaml"))
    args = parser.parse_args(argv)
    if args.gpus < 2:
        parser.error("DDP requires at least two processes; single GPU uses single_gpu.yaml")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_ddp(args.gpus, args.mixed_precision))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
