"""
config_gen/accel_gen.py
----------------
Generate accelerate launch configs.

This is the "how do I spawn processes across GPUs" config — a different
layer from config_gen/config_gen.py (which generates training hyperparameter
configs).

Two strategies:
    ddp     plain DistributedDataParallel — model replicated on each GPU.
            Right choice for 125m and 350m on any GPU count, and 1b on
            ≤ 4 GPUs with high VRAM (H200, B200).

    fsdp    FullyShardedDataParallel — model and optimizer state sharded
            across GPUs. Right choice for 1b on ≥ 4 GPUs to free up
            VRAM for larger micro-batches and avoid gradient checkpointing.

Usage:
    python -m config_gen.accel_gen --strategy ddp  --gpus 8
    python -m config_gen.accel_gen --strategy fsdp --gpus 8

Writes to accelerate_configs/{multi_gpu,fsdp}.yaml by default.
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path
from typing import Optional


# Layer class to wrap with FSDP. The model in model/block.py defines this.
DEFAULT_FSDP_TRANSFORMER_LAYER = "SLMBlock"


# ── DDP ──────────────────────────────────────────────────────────────────────

def render_ddp(num_gpus: int, mixed_precision: str = "bf16") -> str:
    timestamp = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""# ─────────────────────────────────────────────────────────────────────────────
# Auto-generated by config_gen/accel_gen.py
# Strategy:   ddp (DistributedDataParallel — model replicated per GPU)
# Generated:  {timestamp}
#
# Use this when: 125m/350m at any GPU count, 1b on small clusters with
# high-VRAM GPUs (≤ 4× H200/B200).
#
# Use FSDP instead when: 1b on ≥ 4 GPUs and you need bigger micro_batch
# or to drop gradient_checkpointing. Run `make accel-gen-fsdp GPUS=N`.
# ─────────────────────────────────────────────────────────────────────────────
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
enable_cpu_affinity: false
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: {mixed_precision}
num_machines: 1
num_processes: {num_gpus}
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
"""


# ── FSDP ─────────────────────────────────────────────────────────────────────

def render_fsdp(
    num_gpus: int,
    mixed_precision: str = "bf16",
    transformer_layer: str = DEFAULT_FSDP_TRANSFORMER_LAYER,
    sharding_strategy: str = "FULL_SHARD",
    cpu_offload: bool = False,
) -> str:
    timestamp = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""# ─────────────────────────────────────────────────────────────────────────────
# Auto-generated by config_gen/accel_gen.py
# Strategy:   fsdp (FullyShardedDataParallel — model+optimizer state sharded)
# Generated:  {timestamp}
#
# Sharding strategy: {sharding_strategy}
#   FULL_SHARD       — shards weights, grads, and optimizer state.
#                      Maximum memory savings; standard choice for 1b training.
#   SHARD_GRAD_OP    — shards grads and optimizer state only. Faster, less savings.
#   HYBRID_SHARD     — full shard within node, replicate across nodes.
#                      Use only for multi-node clusters.
#
# CPU offload: {cpu_offload}
#   When true, parameters are offloaded to CPU RAM between forward passes.
#   Big VRAM savings, large speed cost. Use only if FULL_SHARD still doesn't fit.
#
# Wrap policy targets layer class: {transformer_layer}
#   This must match the transformer block class name in model/block.py.
#   Each layer becomes a shard unit; FSDP gathers parameters at use-time.
# ─────────────────────────────────────────────────────────────────────────────
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
enable_cpu_affinity: false
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: {mixed_precision}
num_machines: 1
num_processes: {num_gpus}
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: {transformer_layer}
  fsdp_sharding_strategy: {sharding_strategy}
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_offload_params: {str(cpu_offload).lower()}
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_forward_prefetch: false
  fsdp_use_orig_params: true
  fsdp_cpu_ram_efficient_loading: true
  fsdp_sync_module_states: true
  fsdp_activation_checkpointing: false
"""


# ── CLI ──────────────────────────────────────────────────────────────────────

DEFAULT_OUTPUT_BY_STRATEGY = {
    "ddp":  Path("accelerate_configs/multi_gpu.yaml"),
    "fsdp": Path("accelerate_configs/fsdp.yaml"),
}


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate an accelerate launch config.",
    )
    parser.add_argument("--strategy", choices=["ddp", "fsdp"], required=True)
    parser.add_argument("--gpus", type=int, required=True)
    parser.add_argument("--mixed-precision", choices=["bf16", "fp16", "no"],
                        default="bf16")

    parser.add_argument("--transformer-layer", default=DEFAULT_FSDP_TRANSFORMER_LAYER,
                        help="(FSDP only) Transformer block class name to wrap. "
                             "Must match the class in model/block.py.")
    parser.add_argument("--sharding-strategy",
                        choices=["FULL_SHARD", "SHARD_GRAD_OP", "HYBRID_SHARD"],
                        default="FULL_SHARD",
                        help="(FSDP only)")
    parser.add_argument("--cpu-offload", action="store_true",
                        help="(FSDP only) Offload parameters to CPU RAM. "
                             "Big VRAM savings, large speed cost.")

    parser.add_argument("--output", "-o", type=Path, default=None,
                        help="Output file. Defaults based on --strategy.")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)

    if args.gpus < 1:
        print("ERROR: --gpus must be >= 1", file=sys.stderr)
        return 1

    if args.strategy == "ddp":
        text = render_ddp(args.gpus, mixed_precision=args.mixed_precision)
    else:  # fsdp
        text = render_fsdp(
            num_gpus=args.gpus,
            mixed_precision=args.mixed_precision,
            transformer_layer=args.transformer_layer,
            sharding_strategy=args.sharding_strategy,
            cpu_offload=args.cpu_offload,
        )

    output = args.output or DEFAULT_OUTPUT_BY_STRATEGY[args.strategy]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text)
    if not args.quiet:
        print(f"Wrote {output}", file=sys.stderr)
        print(f"  strategy: {args.strategy}", file=sys.stderr)
        print(f"  num_processes: {args.gpus}", file=sys.stderr)
        if args.strategy == "fsdp":
            print(f"  sharding_strategy: {args.sharding_strategy}", file=sys.stderr)
            print(f"  transformer_layer: {args.transformer_layer}", file=sys.stderr)
            print(f"  cpu_offload: {args.cpu_offload}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())